srai a4, s2, 53
lui a6, 0x4000
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
lwu ra, 128(s2)
sw s2, -537(ra)
lwu ra, 932(s2)
lwu ra, 932(a6)
lwu ra, 932(s2)
lwu ra, 932(s2)
lwu ra, 932(s2)
srlw t5, s2, ra
# srai a4, t4, 2
# lwu ra, 932(s2)
# lwu ra, 932(s2)
# lwu ra, 932(s2)
# lwu ra, 932(s2)
# lwu ra, 932(s2)
# lwu ra, 932(s2)
# lwu ra, 932(s2)
# lwu ra, 932(ra)
# sltu s2, s11, ra
# lbu ra, 1024(tp)
# lwu ra, 932(s2)
# sh s0, -1465(ra)
# subw a1, ra, ra
# subw a1, ra, ra
# sw a5, -415(ra)
# subw a1, t2, ra
# slliw t5, ra, 1
# # bgt ra, a1, -2460 # 0x800036fa
# slliw t5, ra, 1
# lwu ra, 932(s2)
unimp
